# Generated by Django 3.1.7 on 2021-06-19 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funds', '0011_auto_20210619_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_name', models.TextField(max_length=100)),
                ('co_short_name', models.TextField(max_length=25, null=True)),
                ('co_reg_no', models.TextField(max_length=50)),
                ('co_description', models.TextField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='continent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continent_name', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_name', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_name', models.TextField(max_length=100)),
                ('inst_description', models.TextField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='perf_categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perf_status', models.TextField(max_length=50)),
                ('Perf_status_descr', models.TextField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='investment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_commitment', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('inv_disbursed', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('inv_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investments.company')),
                ('inv_fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funds.fund')),
                ('perf_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='investments.perf_categories')),
            ],
        ),
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.TextField(max_length=100)),
                ('country_continent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='investments.continent')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='co_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='investments.country'),
        ),
        migrations.AddField(
            model_name='company',
            name='co_industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='investments.industry'),
        ),
    ]
