# Generated by Django 3.1.7 on 2021-06-19 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0003_auto_20210425_2246'),
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='instrument',
        ),
        migrations.AddField(
            model_name='investment',
            name='inv_instrument',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='instruments.instrument'),
        ),
    ]
