# Generated by Django 3.1.7 on 2021-06-19 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_auto_20210619_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='co_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='co_reg_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='co_short_name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='continent',
            name='continent_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='industry',
            name='industry_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='perf_categories',
            name='Perf_status_descr',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='perf_categories',
            name='perf_status',
            field=models.CharField(max_length=25),
        ),
    ]
