# Generated by Django 3.1.7 on 2022-04-25 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0005_deal_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='inv_stage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='investments.deal_stage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='investment',
            name='perf_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investments.perf_categories'),
        ),
    ]
