# Generated by Django 3.1.7 on 2021-04-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0002_auto_20210425_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='description',
            field=models.TextField(default='no descr...', null=True),
        ),
    ]
