# Generated by Django 3.1.7 on 2021-05-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='contact_email',
            field=models.EmailField(default='', max_length=100),
        ),
    ]
