# Generated by Django 3.1.7 on 2021-06-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0002_investor_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='address',
            field=models.TextField(max_length=200),
        ),
    ]
