# Generated by Django 3.1.7 on 2021-06-27 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0003_auto_20210627_0918'),
    ]

    operations = [
        migrations.CreateModel(
            name='investor_contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=50)),
                ('c_email', models.EmailField(max_length=50)),
                ('c_phone', models.CharField(max_length=15, null=True)),
                ('c_key_contact', models.BooleanField(default=False)),
                ('c_adv_board', models.BooleanField(default=False)),
                ('c_inv_comm', models.BooleanField(default=False)),
                ('c_reports', models.BooleanField(default=True)),
                ('c_investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investors.investor')),
            ],
        ),
    ]
