# Generated by Django 3.1.7 on 2021-06-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0005_auto_20210627_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='address',
            field=models.CharField(max_length=200),
        ),
    ]
