# Generated by Django 3.1.7 on 2022-04-30 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0006_auto_20210627_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='investor_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('inv_file', models.FileField(upload_to='')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investors.investor')),
            ],
        ),
    ]
