# Generated by Django 3.1.7 on 2022-04-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0007_investor_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor_file',
            name='inv_file',
            field=models.FileField(upload_to='investors/'),
        ),
    ]
