# Generated by Django 3.1.7 on 2021-04-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='divest_period_extension_cond',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fund',
            name='divestment_period',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fund',
            name='final_close_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='fund',
            name='final_close_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='first_close_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='fund',
            name='first_close_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='inv_period_extension_cond',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fund',
            name='investment_period',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fund',
            name='life',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fund',
            name='target_commitment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='fund',
            name='objective',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
