# Generated by Django 3.1.7 on 2021-04-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0004_auto_20210425_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='final_close_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fund',
            name='first_close_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
