# Generated by Django 3.1.7 on 2021-05-08 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0005_auto_20210425_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='f_structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='fund',
            name='commitment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='fund',
            name='distributions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='fund',
            name='drawn_capital',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='fund',
            name='portfolio_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fund',
            name='undrawn_capital',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='fund',
            name='structure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='funds.f_structure'),
        ),
    ]
