# Generated by Django 3.1.7 on 2021-06-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0009_auto_20210612_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='life',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
