# Generated by Django 3.1.7 on 2021-10-23 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0006_auto_20210627_1020'),
        ('funds', '0011_auto_20210619_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='f_close',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('c_count', models.IntegerField(default=0)),
                ('c_fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funds.fund')),
                ('c_investor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='investors.investor')),
            ],
        ),
    ]
